use serde::Serialize;
use std::{collections::HashMap, sync::Mutex};

const MAX_TRACKED_LOADS: usize = 128;

#[derive(Clone, Debug, Serialize)]
pub struct LoadStatus {
    schema_version: &'static str,
    state: &'static str,
    stage: String,
    detail: String,
    cache: &'static str,
}

impl LoadStatus {
    fn waiting() -> Self {
        Self {
            schema_version: "burr.load-status.v1",
            state: "waiting",
            stage: "Waiting for Burr".to_string(),
            detail: "The viewer request has not started yet.".to_string(),
            cache: "unknown",
        }
    }
}

#[derive(Debug)]
struct TrackedLoad {
    order: u64,
    status: LoadStatus,
}

#[derive(Debug, Default)]
pub struct LoadTracker {
    entries: Mutex<HashMap<String, TrackedLoad>>,
    next_order: Mutex<u64>,
}

impl LoadTracker {
    pub fn reporter<'a>(&'a self, id: Option<&str>) -> LoadReporter<'a> {
        LoadReporter {
            tracker: self,
            id: id.map(ToOwned::to_owned),
        }
    }

    pub fn status(&self, id: &str) -> LoadStatus {
        self.entries
            .lock()
            .ok()
            .and_then(|entries| entries.get(id).map(|entry| entry.status.clone()))
            .unwrap_or_else(LoadStatus::waiting)
    }

    fn update(&self, id: &str, status: LoadStatus) {
        let order = self
            .next_order
            .lock()
            .map(|mut next| {
                *next = next.saturating_add(1);
                *next
            })
            .unwrap_or(0);
        let Ok(mut entries) = self.entries.lock() else {
            return;
        };
        entries.insert(id.to_string(), TrackedLoad { order, status });
        if entries.len() > MAX_TRACKED_LOADS {
            let oldest = entries
                .iter()
                .min_by_key(|(_, entry)| entry.order)
                .map(|(id, _)| id.clone());
            if let Some(oldest) = oldest {
                entries.remove(&oldest);
            }
        }
    }
}

#[derive(Debug)]
pub struct LoadReporter<'a> {
    tracker: &'a LoadTracker,
    id: Option<String>,
}

impl LoadReporter<'_> {
    pub fn start(&self, model: &str) {
        self.set(
            "loading",
            "Reading source",
            &format!("Checking {model} and its reusable viewer cache."),
            "miss",
        );
    }

    pub fn stage(&self, stage: &str, detail: &str) {
        self.set("loading", stage, detail, "miss");
    }

    pub fn ready(&self, cache: &'static str) {
        let detail = match cache {
            "memory" => "Reused the viewer already open in this Burr process.",
            "disk" => "Reused the viewer generated by an earlier Burr process.",
            _ => "The model viewer is ready.",
        };
        self.set("ready", "Opening viewer", detail, cache);
    }

    pub fn failed(&self, detail: &str) {
        self.set("error", "Could not prepare model", detail, "miss");
    }

    fn set(&self, state: &'static str, stage: &str, detail: &str, cache: &'static str) {
        let Some(id) = self.id.as_deref() else {
            return;
        };
        self.tracker.update(
            id,
            LoadStatus {
                schema_version: "burr.load-status.v1",
                state,
                stage: stage.to_string(),
                detail: detail.to_string(),
                cache,
            },
        );
    }
}

pub fn valid_load_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 80
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reports_real_stages_and_cache_outcome() {
        let tracker = LoadTracker::default();
        let reporter = tracker.reporter(Some("tab-1"));
        reporter.start("part.step");
        assert_eq!(tracker.status("tab-1").state, "loading");
        assert_eq!(tracker.status("tab-1").stage, "Reading source");

        reporter.stage("Tessellating geometry", "Look is compiling part.step.");
        assert_eq!(tracker.status("tab-1").stage, "Tessellating geometry");
        reporter.ready("disk");
        assert_eq!(tracker.status("tab-1").state, "ready");
        assert_eq!(tracker.status("tab-1").cache, "disk");
    }

    #[test]
    fn rejects_unbounded_or_unsafe_load_ids() {
        assert!(valid_load_id("tab-1_2"));
        assert!(!valid_load_id(""));
        assert!(!valid_load_id("tab/1"));
        assert!(!valid_load_id(&"a".repeat(81)));
    }
}
